/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.lexer;

import java.io.*;
import compilador.node.*;

@SuppressWarnings("nls")
public class Lexer
{
    protected Token token;
    protected State state = State.INITIAL;

    private IPushbackReader in;
    private int line;
    private int pos;
    private boolean cr;
    private boolean eof;
    private final StringBuffer text = new StringBuffer();

    @SuppressWarnings("unused")
    protected void filter() throws LexerException, IOException
    {
        // Do nothing
    }

    public Lexer(@SuppressWarnings("hiding") final PushbackReader in)
    {
        this.in = new IPushbackReader() {

            private PushbackReader pushbackReader = in;
            
            @Override
            public void unread(int c) throws IOException {
                pushbackReader.unread(c);
            }
            
            @Override
            public int read() throws IOException {
                return pushbackReader.read();
            }
        };
    }
 
    public Lexer(@SuppressWarnings("hiding") IPushbackReader in)
    {
        this.in = in;
    }
 
    public Token peek() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        return this.token;
    }

    public Token next() throws LexerException, IOException
    {
        while(this.token == null)
        {
            this.token = getToken();
            filter();
        }

        Token result = this.token;
        this.token = null;
        return result;
    }

    protected Token getToken() throws IOException, LexerException
    {
        int dfa_state = 0;

        int start_pos = this.pos;
        int start_line = this.line;

        int accept_state = -1;
        int accept_token = -1;
        int accept_length = -1;
        int accept_pos = -1;
        int accept_line = -1;

        @SuppressWarnings("hiding") int[][][] gotoTable = Lexer.gotoTable[this.state.id()];
        @SuppressWarnings("hiding") int[] accept = Lexer.accept[this.state.id()];
        this.text.setLength(0);

        while(true)
        {
            int c = getChar();

            if(c != -1)
            {
                switch(c)
                {
                case 10:
                    if(this.cr)
                    {
                        this.cr = false;
                    }
                    else
                    {
                        this.line++;
                        this.pos = 0;
                    }
                    break;
                case 13:
                    this.line++;
                    this.pos = 0;
                    this.cr = true;
                    break;
                default:
                    this.pos++;
                    this.cr = false;
                    break;
                }

                this.text.append((char) c);

                do
                {
                    int oldState = (dfa_state < -1) ? (-2 -dfa_state) : dfa_state;

                    dfa_state = -1;

                    int[][] tmp1 =  gotoTable[oldState];
                    int low = 0;
                    int high = tmp1.length - 1;

                    while(low <= high)
                    {
                        // int middle = (low + high) / 2;
                        int middle = (low + high) >>> 1;
                        int[] tmp2 = tmp1[middle];

                        if(c < tmp2[0])
                        {
                            high = middle - 1;
                        }
                        else if(c > tmp2[1])
                        {
                            low = middle + 1;
                        }
                        else
                        {
                            dfa_state = tmp2[2];
                            break;
                        }
                    }
                }while(dfa_state < -1);
            }
            else
            {
                dfa_state = -1;
            }

            if(dfa_state >= 0)
            {
                if(accept[dfa_state] != -1)
                {
                    accept_state = dfa_state;
                    accept_token = accept[dfa_state];
                    accept_length = this.text.length();
                    accept_pos = this.pos;
                    accept_line = this.line;
                }
            }
            else
            {
                if(accept_state != -1)
                {
                    switch(accept_token)
                    {
                    case 0:
                        {
                            @SuppressWarnings("hiding") Token token = new0(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 1:
                        {
                            @SuppressWarnings("hiding") Token token = new1(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 2:
                        {
                            @SuppressWarnings("hiding") Token token = new2(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 3:
                        {
                            @SuppressWarnings("hiding") Token token = new3(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 4:
                        {
                            @SuppressWarnings("hiding") Token token = new4(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 5:
                        {
                            @SuppressWarnings("hiding") Token token = new5(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 6:
                        {
                            @SuppressWarnings("hiding") Token token = new6(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 7:
                        {
                            @SuppressWarnings("hiding") Token token = new7(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 8:
                        {
                            @SuppressWarnings("hiding") Token token = new8(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 9:
                        {
                            @SuppressWarnings("hiding") Token token = new9(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    case 10:
                        {
                            @SuppressWarnings("hiding") Token token = new10(
                                getText(accept_length),
                                start_line + 1,
                                start_pos + 1);
                            pushBack(accept_length);
                            this.pos = accept_pos;
                            this.line = accept_line;
                            return token;
                        }
                    }
                }
                else
                {
                    if(this.text.length() > 0)
                    {
                        throw new LexerException(
                            new InvalidToken(this.text.substring(0, 1), start_line + 1, start_pos + 1),
                            "[" + (start_line + 1) + "," + (start_pos + 1) + "]" +
                            " Unknown token: " + this.text);
                    }

                    @SuppressWarnings("hiding") EOF token = new EOF(
                        start_line + 1,
                        start_pos + 1);
                    return token;
                }
            }
        }
    }

    Token new0(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TNomePrograma(text, line, pos); }
    Token new1(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TEol(text, line, pos); }
    Token new2(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPonto(text, line, pos); }
    Token new3(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDoispontos(text, line, pos); }
    Token new4(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TPrograma(text, line, pos); }
    Token new5(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TInicio(text, line, pos); }
    Token new6(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TFim(text, line, pos); }
    Token new7(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TVar(text, line, pos); }
    Token new8(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TDefTipo(text, line, pos); }
    Token new9(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioLinha(text, line, pos); }
    Token new10(@SuppressWarnings("hiding") String text, @SuppressWarnings("hiding") int line, @SuppressWarnings("hiding") int pos) { return new TComentarioBloco(text, line, pos); }

    private int getChar() throws IOException
    {
        if(this.eof)
        {
            return -1;
        }

        int result = this.in.read();

        if(result == -1)
        {
            this.eof = true;
        }

        return result;
    }

    private void pushBack(int acceptLength) throws IOException
    {
        int length = this.text.length();
        for(int i = length - 1; i >= acceptLength; i--)
        {
            this.eof = false;

            this.in.unread(this.text.charAt(i));
        }
    }

    protected void unread(@SuppressWarnings("hiding") Token token) throws IOException
    {
        @SuppressWarnings("hiding") String text = token.getText();
        int length = text.length();

        for(int i = length - 1; i >= 0; i--)
        {
            this.eof = false;

            this.in.unread(text.charAt(i));
        }

        this.pos = token.getPos() - 1;
        this.line = token.getLine() - 1;
    }

    private String getText(int acceptLength)
    {
        StringBuffer s = new StringBuffer(acceptLength);
        for(int i = 0; i < acceptLength; i++)
        {
            s.append(this.text.charAt(i));
        }

        return s.toString();
    }

    private static int[][][][] gotoTable;
/*  {
        { // INITIAL
            {{10, 10, 1}, {13, 13, 2}, {32, 32, 3}, {46, 46, 4}, {47, 47, 5}, {58, 58, 6}, {59, 59, 7}, {65, 90, 8}, {92, 92, 9}, {99, 99, 10}, {102, 102, 11}, {105, 105, 12}, {112, 112, 13}, {114, 114, 14}, {118, 118, 15}, },
            {{10, 46, -2}, {58, 59, -2}, {92, 118, -2}, },
            {{10, 118, -3}, },
            {{10, 118, -3}, },
            {},
            {{42, 42, 16}, {47, 47, 17}, },
            {{10, 10, 18}, {13, 13, 19}, {32, 32, 20}, {92, 92, 21}, },
            {{10, 10, 22}, {13, 13, 23}, {32, 32, 24}, {92, 92, 25}, },
            {{65, 90, 26}, {97, 122, 27}, },
            {{110, 110, 28}, },
            {{97, 97, 29}, },
            {{105, 105, 30}, },
            {{110, 110, 31}, },
            {{114, 114, 32}, },
            {{101, 101, 33}, },
            {{97, 97, 34}, },
            {{0, 9, 35}, {10, 10, 36}, {11, 12, 35}, {13, 13, 37}, {14, 31, 35}, {32, 32, 38}, {33, 41, 35}, {42, 42, 39}, {43, 91, 35}, {92, 92, 40}, {93, 65535, 35}, },
            {{0, 9, 41}, {10, 10, 42}, {11, 12, 41}, {13, 13, 43}, {14, 31, 41}, {32, 32, 44}, {33, 91, 41}, {92, 92, 45}, {93, 65535, 41}, },
            {{10, 92, -8}, },
            {{10, 92, -8}, },
            {{10, 92, -8}, },
            {{110, 110, 46}, },
            {{10, 92, -9}, },
            {{10, 92, -9}, },
            {{10, 92, -9}, },
            {{110, 110, 47}, },
            {{65, 122, -10}, },
            {{65, 90, 48}, {97, 122, 27}, },
            {{10, 118, -3}, },
            {{114, 114, 49}, },
            {{109, 109, 50}, },
            {{105, 105, 51}, {116, 116, 52}, },
            {{111, 111, 53}, },
            {{97, 97, 54}, },
            {{114, 114, 55}, },
            {{0, 65535, -18}, },
            {{0, 65535, -18}, },
            {{0, 65535, -18}, },
            {{0, 65535, -18}, },
            {{0, 91, -18}, {92, 92, 56}, {93, 65535, 35}, },
            {{0, 92, -18}, {93, 109, 35}, {110, 110, 57}, {111, 65535, 35}, },
            {{0, 65535, -19}, },
            {{0, 65535, -19}, },
            {{0, 65535, -19}, },
            {{0, 65535, -19}, },
            {{0, 92, -19}, {93, 109, 41}, {110, 110, 58}, {111, 65535, 41}, },
            {{10, 92, -8}, },
            {{10, 92, -9}, },
            {{65, 122, -29}, },
            {{97, 97, 59}, },
            {{10, 10, 60}, {13, 13, 61}, {32, 32, 62}, {92, 92, 63}, },
            {{99, 99, 64}, },
            {{101, 101, 65}, },
            {{103, 103, 66}, },
            {{108, 108, 67}, },
            {{10, 10, 68}, {13, 13, 69}, {32, 32, 70}, {92, 92, 71}, },
            {{0, 9, 35}, {10, 10, 72}, {11, 12, 35}, {13, 13, 73}, {14, 31, 35}, {32, 32, 74}, {33, 91, -18}, {92, 92, 75}, {93, 65535, -42}, },
            {{0, 65535, -18}, },
            {{0, 65535, -19}, },
            {{99, 99, 76}, },
            {{10, 92, -52}, },
            {{10, 92, -52}, },
            {{10, 92, -52}, },
            {{110, 110, 77}, },
            {{105, 105, 78}, },
            {{105, 105, 79}, },
            {{114, 114, 80}, },
            {{10, 10, 81}, {13, 13, 82}, {32, 32, 83}, {92, 92, 84}, },
            {{10, 32, -57}, {58, 58, 85}, {92, 92, 71}, },
            {{10, 92, -70}, },
            {{10, 92, -70}, },
            {{110, 110, 86}, },
            {{0, 92, -58}, {93, 65535, 35}, },
            {{0, 65535, -74}, },
            {{0, 65535, -74}, },
            {{0, 109, -42}, {110, 110, 87}, {111, 65535, 35}, },
            {{116, 116, 88}, },
            {{10, 92, -52}, },
            {{111, 111, 89}, },
            {{114, 114, 90}, },
            {{97, 97, 91}, },
            {{10, 92, -69}, },
            {{10, 92, -69}, },
            {{10, 92, -69}, },
            {{110, 110, 92}, },
            {},
            {{10, 92, -70}, },
            {{0, 65535, -74}, },
            {{101, 101, 93}, },
            {{10, 10, 94}, {13, 13, 95}, {32, 32, 96}, {92, 92, 97}, },
            {{111, 111, 98}, },
            {{109, 109, 99}, },
            {{10, 92, -69}, },
            {{114, 114, 100}, },
            {{10, 92, -91}, },
            {{10, 92, -91}, },
            {{10, 92, -91}, },
            {{110, 110, 101}, },
            {{10, 92, -69}, },
            {{97, 97, 102}, },
            {{101, 101, 103}, },
            {{10, 92, -91}, },
            {{10, 10, 104}, {13, 13, 105}, {32, 32, 106}, {92, 92, 107}, },
            {{10, 92, -69}, },
            {{10, 92, -104}, },
            {{10, 92, -104}, },
            {{10, 92, -104}, },
            {{110, 110, 108}, },
            {{10, 92, -104}, },
        }
    };*/

    private static int[][] accept;
/*  {
        // INITIAL
        {-1, -1, -1, -1, 2, -1, 3, 1, 0, -1, -1, -1, -1, -1, -1, -1, -1, 9, 3, 3, 3, -1, 1, 1, 1, -1, 0, 0, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, 9, 9, 9, 9, 9, 3, 1, 0, -1, 6, -1, -1, -1, -1, -1, 10, -1, 9, -1, 6, 6, 6, -1, -1, -1, -1, 8, -1, -1, -1, -1, 10, 10, 10, -1, -1, 6, -1, -1, -1, 8, 8, 8, -1, 7, -1, 10, -1, 5, -1, -1, 8, -1, 5, 5, 5, -1, 8, -1, -1, 5, -1, 8, 4, 4, 4, -1, 4, },

    };*/

    public static class State
    {
        public final static State INITIAL = new State(0);

        private int id;

        private State(@SuppressWarnings("hiding") int id)
        {
            this.id = id;
        }

        public int id()
        {
            return this.id;
        }
    }

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Lexer.class.getResourceAsStream("lexer.dat")));

            // read gotoTable
            int length = s.readInt();
            gotoTable = new int[length][][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][][];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                    length = s.readInt();
                    gotoTable[i][j] = new int[length][3];
                    for(int k = 0; k < gotoTable[i][j].length; k++)
                    {
                        for(int l = 0; l < 3; l++)
                        {
                            gotoTable[i][j][k][l] = s.readInt();
                        }
                    }
                }
            }

            // read accept
            length = s.readInt();
            accept = new int[length][];
            for(int i = 0; i < accept.length; i++)
            {
                length = s.readInt();
                accept[i] = new int[length];
                for(int j = 0; j < accept[i].length; j++)
                {
                    accept[i][j] = s.readInt();
                }
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"lexer.dat\" is either missing or corrupted.");
        }
    }
}
