/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AAteParaSubPasso extends PParaSubPasso
{
    private PParaSubAte _paraSubAte_;

    public AAteParaSubPasso()
    {
        // Constructor
    }

    public AAteParaSubPasso(
        @SuppressWarnings("hiding") PParaSubAte _paraSubAte_)
    {
        // Constructor
        setParaSubAte(_paraSubAte_);

    }

    @Override
    public Object clone()
    {
        return new AAteParaSubPasso(
            cloneNode(this._paraSubAte_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAteParaSubPasso(this);
    }

    public PParaSubAte getParaSubAte()
    {
        return this._paraSubAte_;
    }

    public void setParaSubAte(PParaSubAte node)
    {
        if(this._paraSubAte_ != null)
        {
            this._paraSubAte_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._paraSubAte_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._paraSubAte_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._paraSubAte_ == child)
        {
            this._paraSubAte_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._paraSubAte_ == oldChild)
        {
            setParaSubAte((PParaSubAte) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
