/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ACompTermoRel extends PTermoRel
{
    private PTermoRel _termoRel_;
    private POpRelacionalComp _opRelacionalComp_;
    private PFatorRel _fatorRel_;

    public ACompTermoRel()
    {
        // Constructor
    }

    public ACompTermoRel(
        @SuppressWarnings("hiding") PTermoRel _termoRel_,
        @SuppressWarnings("hiding") POpRelacionalComp _opRelacionalComp_,
        @SuppressWarnings("hiding") PFatorRel _fatorRel_)
    {
        // Constructor
        setTermoRel(_termoRel_);

        setOpRelacionalComp(_opRelacionalComp_);

        setFatorRel(_fatorRel_);

    }

    @Override
    public Object clone()
    {
        return new ACompTermoRel(
            cloneNode(this._termoRel_),
            cloneNode(this._opRelacionalComp_),
            cloneNode(this._fatorRel_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACompTermoRel(this);
    }

    public PTermoRel getTermoRel()
    {
        return this._termoRel_;
    }

    public void setTermoRel(PTermoRel node)
    {
        if(this._termoRel_ != null)
        {
            this._termoRel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoRel_ = node;
    }

    public POpRelacionalComp getOpRelacionalComp()
    {
        return this._opRelacionalComp_;
    }

    public void setOpRelacionalComp(POpRelacionalComp node)
    {
        if(this._opRelacionalComp_ != null)
        {
            this._opRelacionalComp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opRelacionalComp_ = node;
    }

    public PFatorRel getFatorRel()
    {
        return this._fatorRel_;
    }

    public void setFatorRel(PFatorRel node)
    {
        if(this._fatorRel_ != null)
        {
            this._fatorRel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fatorRel_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termoRel_)
            + toString(this._opRelacionalComp_)
            + toString(this._fatorRel_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termoRel_ == child)
        {
            this._termoRel_ = null;
            return;
        }

        if(this._opRelacionalComp_ == child)
        {
            this._opRelacionalComp_ = null;
            return;
        }

        if(this._fatorRel_ == child)
        {
            this._fatorRel_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termoRel_ == oldChild)
        {
            setTermoRel((PTermoRel) newChild);
            return;
        }

        if(this._opRelacionalComp_ == oldChild)
        {
            setOpRelacionalComp((POpRelacionalComp) newChild);
            return;
        }

        if(this._fatorRel_ == oldChild)
        {
            setFatorRel((PFatorRel) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
