/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import java.util.*;
import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ACondicionalSenaoComandos extends PComandos
{
    private PExpressaoLogica _expressaoLogica_;
    private final LinkedList<PComandos> _entaoCmd_ = new LinkedList<PComandos>();
    private final LinkedList<PComandos> _senaoCmd_ = new LinkedList<PComandos>();

    public ACondicionalSenaoComandos()
    {
        // Constructor
    }

    public ACondicionalSenaoComandos(
        @SuppressWarnings("hiding") PExpressaoLogica _expressaoLogica_,
        @SuppressWarnings("hiding") List<?> _entaoCmd_,
        @SuppressWarnings("hiding") List<?> _senaoCmd_)
    {
        // Constructor
        setExpressaoLogica(_expressaoLogica_);

        setEntaoCmd(_entaoCmd_);

        setSenaoCmd(_senaoCmd_);

    }

    @Override
    public Object clone()
    {
        return new ACondicionalSenaoComandos(
            cloneNode(this._expressaoLogica_),
            cloneList(this._entaoCmd_),
            cloneList(this._senaoCmd_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACondicionalSenaoComandos(this);
    }

    public PExpressaoLogica getExpressaoLogica()
    {
        return this._expressaoLogica_;
    }

    public void setExpressaoLogica(PExpressaoLogica node)
    {
        if(this._expressaoLogica_ != null)
        {
            this._expressaoLogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoLogica_ = node;
    }

    public LinkedList<PComandos> getEntaoCmd()
    {
        return this._entaoCmd_;
    }

    public void setEntaoCmd(List<?> list)
    {
        for(PComandos e : this._entaoCmd_)
        {
            e.parent(null);
        }
        this._entaoCmd_.clear();

        for(Object obj_e : list)
        {
            PComandos e = (PComandos) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._entaoCmd_.add(e);
        }
    }

    public LinkedList<PComandos> getSenaoCmd()
    {
        return this._senaoCmd_;
    }

    public void setSenaoCmd(List<?> list)
    {
        for(PComandos e : this._senaoCmd_)
        {
            e.parent(null);
        }
        this._senaoCmd_.clear();

        for(Object obj_e : list)
        {
            PComandos e = (PComandos) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._senaoCmd_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expressaoLogica_)
            + toString(this._entaoCmd_)
            + toString(this._senaoCmd_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expressaoLogica_ == child)
        {
            this._expressaoLogica_ = null;
            return;
        }

        if(this._entaoCmd_.remove(child))
        {
            return;
        }

        if(this._senaoCmd_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expressaoLogica_ == oldChild)
        {
            setExpressaoLogica((PExpressaoLogica) newChild);
            return;
        }

        for(ListIterator<PComandos> i = this._entaoCmd_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PComandos) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        for(ListIterator<PComandos> i = this._senaoCmd_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PComandos) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
