/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ACondicionalParteComandos extends PParteComandos
{
    private PCondicional _condicional_;

    public ACondicionalParteComandos()
    {
        // Constructor
    }

    public ACondicionalParteComandos(
        @SuppressWarnings("hiding") PCondicional _condicional_)
    {
        // Constructor
        setCondicional(_condicional_);

    }

    @Override
    public Object clone()
    {
        return new ACondicionalParteComandos(
            cloneNode(this._condicional_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACondicionalParteComandos(this);
    }

    public PCondicional getCondicional()
    {
        return this._condicional_;
    }

    public void setCondicional(PCondicional node)
    {
        if(this._condicional_ != null)
        {
            this._condicional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._condicional_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._condicional_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._condicional_ == child)
        {
            this._condicional_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._condicional_ == oldChild)
        {
            setCondicional((PCondicional) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
