/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ACondSenao extends PCondSenao
{
    private PCondSenaoSub _condSenaoSub_;

    public ACondSenao()
    {
        // Constructor
    }

    public ACondSenao(
        @SuppressWarnings("hiding") PCondSenaoSub _condSenaoSub_)
    {
        // Constructor
        setCondSenaoSub(_condSenaoSub_);

    }

    @Override
    public Object clone()
    {
        return new ACondSenao(
            cloneNode(this._condSenaoSub_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACondSenao(this);
    }

    public PCondSenaoSub getCondSenaoSub()
    {
        return this._condSenaoSub_;
    }

    public void setCondSenaoSub(PCondSenaoSub node)
    {
        if(this._condSenaoSub_ != null)
        {
            this._condSenaoSub_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._condSenaoSub_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._condSenaoSub_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._condSenaoSub_ == child)
        {
            this._condSenaoSub_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._condSenaoSub_ == oldChild)
        {
            setCondSenaoSub((PCondSenaoSub) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
