/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import java.util.*;
import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ADeclaracao extends PDeclaracao
{
    private final LinkedList<PParteDeclaracao> _parteDeclaracao_ = new LinkedList<PParteDeclaracao>();

    public ADeclaracao()
    {
        // Constructor
    }

    public ADeclaracao(
        @SuppressWarnings("hiding") List<?> _parteDeclaracao_)
    {
        // Constructor
        setParteDeclaracao(_parteDeclaracao_);

    }

    @Override
    public Object clone()
    {
        return new ADeclaracao(
            cloneList(this._parteDeclaracao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADeclaracao(this);
    }

    public LinkedList<PParteDeclaracao> getParteDeclaracao()
    {
        return this._parteDeclaracao_;
    }

    public void setParteDeclaracao(List<?> list)
    {
        for(PParteDeclaracao e : this._parteDeclaracao_)
        {
            e.parent(null);
        }
        this._parteDeclaracao_.clear();

        for(Object obj_e : list)
        {
            PParteDeclaracao e = (PParteDeclaracao) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._parteDeclaracao_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._parteDeclaracao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._parteDeclaracao_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        for(ListIterator<PParteDeclaracao> i = this._parteDeclaracao_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PParteDeclaracao) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
