/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AExpRelTermoLog extends PTermoLog
{
    private PExpRel _expRel_;

    public AExpRelTermoLog()
    {
        // Constructor
    }

    public AExpRelTermoLog(
        @SuppressWarnings("hiding") PExpRel _expRel_)
    {
        // Constructor
        setExpRel(_expRel_);

    }

    @Override
    public Object clone()
    {
        return new AExpRelTermoLog(
            cloneNode(this._expRel_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpRelTermoLog(this);
    }

    public PExpRel getExpRel()
    {
        return this._expRel_;
    }

    public void setExpRel(PExpRel node)
    {
        if(this._expRel_ != null)
        {
            this._expRel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expRel_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expRel_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expRel_ == child)
        {
            this._expRel_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expRel_ == oldChild)
        {
            setExpRel((PExpRel) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
