/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AFatorRelTermoRel extends PTermoRel
{
    private PFatorRel _fatorRel_;

    public AFatorRelTermoRel()
    {
        // Constructor
    }

    public AFatorRelTermoRel(
        @SuppressWarnings("hiding") PFatorRel _fatorRel_)
    {
        // Constructor
        setFatorRel(_fatorRel_);

    }

    @Override
    public Object clone()
    {
        return new AFatorRelTermoRel(
            cloneNode(this._fatorRel_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFatorRelTermoRel(this);
    }

    public PFatorRel getFatorRel()
    {
        return this._fatorRel_;
    }

    public void setFatorRel(PFatorRel node)
    {
        if(this._fatorRel_ != null)
        {
            this._fatorRel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fatorRel_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._fatorRel_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._fatorRel_ == child)
        {
            this._fatorRel_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._fatorRel_ == oldChild)
        {
            setFatorRel((PFatorRel) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
