/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AFatorTermo2 extends PTermo2
{
    private PFator2 _fator2_;

    public AFatorTermo2()
    {
        // Constructor
    }

    public AFatorTermo2(
        @SuppressWarnings("hiding") PFator2 _fator2_)
    {
        // Constructor
        setFator2(_fator2_);

    }

    @Override
    public Object clone()
    {
        return new AFatorTermo2(
            cloneNode(this._fator2_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFatorTermo2(this);
    }

    public PFator2 getFator2()
    {
        return this._fator2_;
    }

    public void setFator2(PFator2 node)
    {
        if(this._fator2_ != null)
        {
            this._fator2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fator2_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._fator2_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._fator2_ == child)
        {
            this._fator2_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._fator2_ == oldChild)
        {
            setFator2((PFator2) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
