/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AFr1FatorRel extends PFatorRel
{
    private PParen _paren_;

    public AFr1FatorRel()
    {
        // Constructor
    }

    public AFr1FatorRel(
        @SuppressWarnings("hiding") PParen _paren_)
    {
        // Constructor
        setParen(_paren_);

    }

    @Override
    public Object clone()
    {
        return new AFr1FatorRel(
            cloneNode(this._paren_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFr1FatorRel(this);
    }

    public PParen getParen()
    {
        return this._paren_;
    }

    public void setParen(PParen node)
    {
        if(this._paren_ != null)
        {
            this._paren_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._paren_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._paren_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._paren_ == child)
        {
            this._paren_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._paren_ == oldChild)
        {
            setParen((PParen) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
