/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AFt2Fator2 extends PFator2
{
    private PFator2 _fator2_;
    private POpRelacional _opRelacional_;
    private PFator3 _fator3_;

    public AFt2Fator2()
    {
        // Constructor
    }

    public AFt2Fator2(
        @SuppressWarnings("hiding") PFator2 _fator2_,
        @SuppressWarnings("hiding") POpRelacional _opRelacional_,
        @SuppressWarnings("hiding") PFator3 _fator3_)
    {
        // Constructor
        setFator2(_fator2_);

        setOpRelacional(_opRelacional_);

        setFator3(_fator3_);

    }

    @Override
    public Object clone()
    {
        return new AFt2Fator2(
            cloneNode(this._fator2_),
            cloneNode(this._opRelacional_),
            cloneNode(this._fator3_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAFt2Fator2(this);
    }

    public PFator2 getFator2()
    {
        return this._fator2_;
    }

    public void setFator2(PFator2 node)
    {
        if(this._fator2_ != null)
        {
            this._fator2_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fator2_ = node;
    }

    public POpRelacional getOpRelacional()
    {
        return this._opRelacional_;
    }

    public void setOpRelacional(POpRelacional node)
    {
        if(this._opRelacional_ != null)
        {
            this._opRelacional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opRelacional_ = node;
    }

    public PFator3 getFator3()
    {
        return this._fator3_;
    }

    public void setFator3(PFator3 node)
    {
        if(this._fator3_ != null)
        {
            this._fator3_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._fator3_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._fator2_)
            + toString(this._opRelacional_)
            + toString(this._fator3_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._fator2_ == child)
        {
            this._fator2_ = null;
            return;
        }

        if(this._opRelacional_ == child)
        {
            this._opRelacional_ = null;
            return;
        }

        if(this._fator3_ == child)
        {
            this._fator3_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._fator2_ == oldChild)
        {
            setFator2((PFator2) newChild);
            return;
        }

        if(this._opRelacional_ == oldChild)
        {
            setOpRelacional((POpRelacional) newChild);
            return;
        }

        if(this._fator3_ == oldChild)
        {
            setFator3((PFator3) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
