/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AIdvirgulaIdVirgula extends PIdVirgula
{
    private TIdentificador _identificador_;
    private PIdVirgula _idVirgula_;

    public AIdvirgulaIdVirgula()
    {
        // Constructor
    }

    public AIdvirgulaIdVirgula(
        @SuppressWarnings("hiding") TIdentificador _identificador_,
        @SuppressWarnings("hiding") PIdVirgula _idVirgula_)
    {
        // Constructor
        setIdentificador(_identificador_);

        setIdVirgula(_idVirgula_);

    }

    @Override
    public Object clone()
    {
        return new AIdvirgulaIdVirgula(
            cloneNode(this._identificador_),
            cloneNode(this._idVirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIdvirgulaIdVirgula(this);
    }

    public TIdentificador getIdentificador()
    {
        return this._identificador_;
    }

    public void setIdentificador(TIdentificador node)
    {
        if(this._identificador_ != null)
        {
            this._identificador_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._identificador_ = node;
    }

    public PIdVirgula getIdVirgula()
    {
        return this._idVirgula_;
    }

    public void setIdVirgula(PIdVirgula node)
    {
        if(this._idVirgula_ != null)
        {
            this._idVirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._idVirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._identificador_)
            + toString(this._idVirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._identificador_ == child)
        {
            this._identificador_ = null;
            return;
        }

        if(this._idVirgula_ == child)
        {
            this._idVirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._identificador_ == oldChild)
        {
            setIdentificador((TIdentificador) newChild);
            return;
        }

        if(this._idVirgula_ == oldChild)
        {
            setIdVirgula((PIdVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
