/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AIfNa2IfNaoAssociado extends PIfNaoAssociado
{
    private TSe _se_;
    private PExpressaoLogica _expressaoLogica_;
    private TEntao _entao_;
    private PIfAssociado _ifAssociado_;
    private TSenao _senao_;
    private PIfNaoAssociado _ifNaoAssociado_;

    public AIfNa2IfNaoAssociado()
    {
        // Constructor
    }

    public AIfNa2IfNaoAssociado(
        @SuppressWarnings("hiding") TSe _se_,
        @SuppressWarnings("hiding") PExpressaoLogica _expressaoLogica_,
        @SuppressWarnings("hiding") TEntao _entao_,
        @SuppressWarnings("hiding") PIfAssociado _ifAssociado_,
        @SuppressWarnings("hiding") TSenao _senao_,
        @SuppressWarnings("hiding") PIfNaoAssociado _ifNaoAssociado_)
    {
        // Constructor
        setSe(_se_);

        setExpressaoLogica(_expressaoLogica_);

        setEntao(_entao_);

        setIfAssociado(_ifAssociado_);

        setSenao(_senao_);

        setIfNaoAssociado(_ifNaoAssociado_);

    }

    @Override
    public Object clone()
    {
        return new AIfNa2IfNaoAssociado(
            cloneNode(this._se_),
            cloneNode(this._expressaoLogica_),
            cloneNode(this._entao_),
            cloneNode(this._ifAssociado_),
            cloneNode(this._senao_),
            cloneNode(this._ifNaoAssociado_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfNa2IfNaoAssociado(this);
    }

    public TSe getSe()
    {
        return this._se_;
    }

    public void setSe(TSe node)
    {
        if(this._se_ != null)
        {
            this._se_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._se_ = node;
    }

    public PExpressaoLogica getExpressaoLogica()
    {
        return this._expressaoLogica_;
    }

    public void setExpressaoLogica(PExpressaoLogica node)
    {
        if(this._expressaoLogica_ != null)
        {
            this._expressaoLogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoLogica_ = node;
    }

    public TEntao getEntao()
    {
        return this._entao_;
    }

    public void setEntao(TEntao node)
    {
        if(this._entao_ != null)
        {
            this._entao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._entao_ = node;
    }

    public PIfAssociado getIfAssociado()
    {
        return this._ifAssociado_;
    }

    public void setIfAssociado(PIfAssociado node)
    {
        if(this._ifAssociado_ != null)
        {
            this._ifAssociado_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ifAssociado_ = node;
    }

    public TSenao getSenao()
    {
        return this._senao_;
    }

    public void setSenao(TSenao node)
    {
        if(this._senao_ != null)
        {
            this._senao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._senao_ = node;
    }

    public PIfNaoAssociado getIfNaoAssociado()
    {
        return this._ifNaoAssociado_;
    }

    public void setIfNaoAssociado(PIfNaoAssociado node)
    {
        if(this._ifNaoAssociado_ != null)
        {
            this._ifNaoAssociado_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ifNaoAssociado_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._se_)
            + toString(this._expressaoLogica_)
            + toString(this._entao_)
            + toString(this._ifAssociado_)
            + toString(this._senao_)
            + toString(this._ifNaoAssociado_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._se_ == child)
        {
            this._se_ = null;
            return;
        }

        if(this._expressaoLogica_ == child)
        {
            this._expressaoLogica_ = null;
            return;
        }

        if(this._entao_ == child)
        {
            this._entao_ = null;
            return;
        }

        if(this._ifAssociado_ == child)
        {
            this._ifAssociado_ = null;
            return;
        }

        if(this._senao_ == child)
        {
            this._senao_ = null;
            return;
        }

        if(this._ifNaoAssociado_ == child)
        {
            this._ifNaoAssociado_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._se_ == oldChild)
        {
            setSe((TSe) newChild);
            return;
        }

        if(this._expressaoLogica_ == oldChild)
        {
            setExpressaoLogica((PExpressaoLogica) newChild);
            return;
        }

        if(this._entao_ == oldChild)
        {
            setEntao((TEntao) newChild);
            return;
        }

        if(this._ifAssociado_ == oldChild)
        {
            setIfAssociado((PIfAssociado) newChild);
            return;
        }

        if(this._senao_ == oldChild)
        {
            setSenao((TSenao) newChild);
            return;
        }

        if(this._ifNaoAssociado_ == oldChild)
        {
            setIfNaoAssociado((PIfNaoAssociado) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
