/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AIfNa1IfNaoAssociado extends PIfNaoAssociado
{
    private TSe _se_;
    private PExpressaoLogica _expressaoLogica_;
    private TSenao _senao_;
    private PCondicional _condicional_;

    public AIfNa1IfNaoAssociado()
    {
        // Constructor
    }

    public AIfNa1IfNaoAssociado(
        @SuppressWarnings("hiding") TSe _se_,
        @SuppressWarnings("hiding") PExpressaoLogica _expressaoLogica_,
        @SuppressWarnings("hiding") TSenao _senao_,
        @SuppressWarnings("hiding") PCondicional _condicional_)
    {
        // Constructor
        setSe(_se_);

        setExpressaoLogica(_expressaoLogica_);

        setSenao(_senao_);

        setCondicional(_condicional_);

    }

    @Override
    public Object clone()
    {
        return new AIfNa1IfNaoAssociado(
            cloneNode(this._se_),
            cloneNode(this._expressaoLogica_),
            cloneNode(this._senao_),
            cloneNode(this._condicional_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfNa1IfNaoAssociado(this);
    }

    public TSe getSe()
    {
        return this._se_;
    }

    public void setSe(TSe node)
    {
        if(this._se_ != null)
        {
            this._se_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._se_ = node;
    }

    public PExpressaoLogica getExpressaoLogica()
    {
        return this._expressaoLogica_;
    }

    public void setExpressaoLogica(PExpressaoLogica node)
    {
        if(this._expressaoLogica_ != null)
        {
            this._expressaoLogica_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expressaoLogica_ = node;
    }

    public TSenao getSenao()
    {
        return this._senao_;
    }

    public void setSenao(TSenao node)
    {
        if(this._senao_ != null)
        {
            this._senao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._senao_ = node;
    }

    public PCondicional getCondicional()
    {
        return this._condicional_;
    }

    public void setCondicional(PCondicional node)
    {
        if(this._condicional_ != null)
        {
            this._condicional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._condicional_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._se_)
            + toString(this._expressaoLogica_)
            + toString(this._senao_)
            + toString(this._condicional_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._se_ == child)
        {
            this._se_ = null;
            return;
        }

        if(this._expressaoLogica_ == child)
        {
            this._expressaoLogica_ = null;
            return;
        }

        if(this._senao_ == child)
        {
            this._senao_ = null;
            return;
        }

        if(this._condicional_ == child)
        {
            this._condicional_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._se_ == oldChild)
        {
            setSe((TSe) newChild);
            return;
        }

        if(this._expressaoLogica_ == oldChild)
        {
            setExpressaoLogica((PExpressaoLogica) newChild);
            return;
        }

        if(this._senao_ == oldChild)
        {
            setSenao((TSenao) newChild);
            return;
        }

        if(this._condicional_ == oldChild)
        {
            setCondicional((PCondicional) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
