/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AIfNaCondicional extends PCondicional
{
    private PIfNaoAssociado _ifNaoAssociado_;

    public AIfNaCondicional()
    {
        // Constructor
    }

    public AIfNaCondicional(
        @SuppressWarnings("hiding") PIfNaoAssociado _ifNaoAssociado_)
    {
        // Constructor
        setIfNaoAssociado(_ifNaoAssociado_);

    }

    @Override
    public Object clone()
    {
        return new AIfNaCondicional(
            cloneNode(this._ifNaoAssociado_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIfNaCondicional(this);
    }

    public PIfNaoAssociado getIfNaoAssociado()
    {
        return this._ifNaoAssociado_;
    }

    public void setIfNaoAssociado(PIfNaoAssociado node)
    {
        if(this._ifNaoAssociado_ != null)
        {
            this._ifNaoAssociado_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._ifNaoAssociado_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._ifNaoAssociado_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._ifNaoAssociado_ == child)
        {
            this._ifNaoAssociado_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._ifNaoAssociado_ == oldChild)
        {
            setIfNaoAssociado((PIfNaoAssociado) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
