/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ALeiaComandos extends PComandos
{
    private PIdVirgula _idVirgula_;

    public ALeiaComandos()
    {
        // Constructor
    }

    public ALeiaComandos(
        @SuppressWarnings("hiding") PIdVirgula _idVirgula_)
    {
        // Constructor
        setIdVirgula(_idVirgula_);

    }

    @Override
    public Object clone()
    {
        return new ALeiaComandos(
            cloneNode(this._idVirgula_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseALeiaComandos(this);
    }

    public PIdVirgula getIdVirgula()
    {
        return this._idVirgula_;
    }

    public void setIdVirgula(PIdVirgula node)
    {
        if(this._idVirgula_ != null)
        {
            this._idVirgula_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._idVirgula_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._idVirgula_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._idVirgula_ == child)
        {
            this._idVirgula_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._idVirgula_ == oldChild)
        {
            setIdVirgula((PIdVirgula) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
