/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ANirNumIntReal extends PNumIntReal
{
    private TNumero _numero_;
    private PParteFrac _parteFrac_;

    public ANirNumIntReal()
    {
        // Constructor
    }

    public ANirNumIntReal(
        @SuppressWarnings("hiding") TNumero _numero_,
        @SuppressWarnings("hiding") PParteFrac _parteFrac_)
    {
        // Constructor
        setNumero(_numero_);

        setParteFrac(_parteFrac_);

    }

    @Override
    public Object clone()
    {
        return new ANirNumIntReal(
            cloneNode(this._numero_),
            cloneNode(this._parteFrac_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANirNumIntReal(this);
    }

    public TNumero getNumero()
    {
        return this._numero_;
    }

    public void setNumero(TNumero node)
    {
        if(this._numero_ != null)
        {
            this._numero_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._numero_ = node;
    }

    public PParteFrac getParteFrac()
    {
        return this._parteFrac_;
    }

    public void setParteFrac(PParteFrac node)
    {
        if(this._parteFrac_ != null)
        {
            this._parteFrac_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._parteFrac_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._numero_)
            + toString(this._parteFrac_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._numero_ == child)
        {
            this._numero_ = null;
            return;
        }

        if(this._parteFrac_ == child)
        {
            this._parteFrac_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._numero_ == oldChild)
        {
            setNumero((TNumero) newChild);
            return;
        }

        if(this._parteFrac_ == oldChild)
        {
            setParteFrac((PParteFrac) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
