/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AOpr2OpRelacional extends POpRelacional
{
    private POpRelacionalComp _opRelacionalComp_;

    public AOpr2OpRelacional()
    {
        // Constructor
    }

    public AOpr2OpRelacional(
        @SuppressWarnings("hiding") POpRelacionalComp _opRelacionalComp_)
    {
        // Constructor
        setOpRelacionalComp(_opRelacionalComp_);

    }

    @Override
    public Object clone()
    {
        return new AOpr2OpRelacional(
            cloneNode(this._opRelacionalComp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOpr2OpRelacional(this);
    }

    public POpRelacionalComp getOpRelacionalComp()
    {
        return this._opRelacionalComp_;
    }

    public void setOpRelacionalComp(POpRelacionalComp node)
    {
        if(this._opRelacionalComp_ != null)
        {
            this._opRelacionalComp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opRelacionalComp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._opRelacionalComp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._opRelacionalComp_ == child)
        {
            this._opRelacionalComp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._opRelacionalComp_ == oldChild)
        {
            setOpRelacionalComp((POpRelacionalComp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
