/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ARepeticaoParteComandos extends PParteComandos
{
    private PRepeticao _repeticao_;

    public ARepeticaoParteComandos()
    {
        // Constructor
    }

    public ARepeticaoParteComandos(
        @SuppressWarnings("hiding") PRepeticao _repeticao_)
    {
        // Constructor
        setRepeticao(_repeticao_);

    }

    @Override
    public Object clone()
    {
        return new ARepeticaoParteComandos(
            cloneNode(this._repeticao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARepeticaoParteComandos(this);
    }

    public PRepeticao getRepeticao()
    {
        return this._repeticao_;
    }

    public void setRepeticao(PRepeticao node)
    {
        if(this._repeticao_ != null)
        {
            this._repeticao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._repeticao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._repeticao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._repeticao_ == child)
        {
            this._repeticao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._repeticao_ == oldChild)
        {
            setRepeticao((PRepeticao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
