/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class AStartStart extends PStart
{
    private PEsqueletoPrograma _esqueletoPrograma_;

    public AStartStart()
    {
        // Constructor
    }

    public AStartStart(
        @SuppressWarnings("hiding") PEsqueletoPrograma _esqueletoPrograma_)
    {
        // Constructor
        setEsqueletoPrograma(_esqueletoPrograma_);

    }

    @Override
    public Object clone()
    {
        return new AStartStart(
            cloneNode(this._esqueletoPrograma_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAStartStart(this);
    }

    public PEsqueletoPrograma getEsqueletoPrograma()
    {
        return this._esqueletoPrograma_;
    }

    public void setEsqueletoPrograma(PEsqueletoPrograma node)
    {
        if(this._esqueletoPrograma_ != null)
        {
            this._esqueletoPrograma_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._esqueletoPrograma_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._esqueletoPrograma_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._esqueletoPrograma_ == child)
        {
            this._esqueletoPrograma_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._esqueletoPrograma_ == oldChild)
        {
            setEsqueletoPrograma((PEsqueletoPrograma) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
