/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ATermoLogExpressaoLogica extends PExpressaoLogica
{
    private PTermoLog _termoLog_;

    public ATermoLogExpressaoLogica()
    {
        // Constructor
    }

    public ATermoLogExpressaoLogica(
        @SuppressWarnings("hiding") PTermoLog _termoLog_)
    {
        // Constructor
        setTermoLog(_termoLog_);

    }

    @Override
    public Object clone()
    {
        return new ATermoLogExpressaoLogica(
            cloneNode(this._termoLog_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATermoLogExpressaoLogica(this);
    }

    public PTermoLog getTermoLog()
    {
        return this._termoLog_;
    }

    public void setTermoLog(PTermoLog node)
    {
        if(this._termoLog_ != null)
        {
            this._termoLog_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoLog_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termoLog_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termoLog_ == child)
        {
            this._termoLog_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termoLog_ == oldChild)
        {
            setTermoLog((PTermoLog) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
