/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ATermoRelExpRel extends PExpRel
{
    private PTermoRel _termoRel_;

    public ATermoRelExpRel()
    {
        // Constructor
    }

    public ATermoRelExpRel(
        @SuppressWarnings("hiding") PTermoRel _termoRel_)
    {
        // Constructor
        setTermoRel(_termoRel_);

    }

    @Override
    public Object clone()
    {
        return new ATermoRelExpRel(
            cloneNode(this._termoRel_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATermoRelExpRel(this);
    }

    public PTermoRel getTermoRel()
    {
        return this._termoRel_;
    }

    public void setTermoRel(PTermoRel node)
    {
        if(this._termoRel_ != null)
        {
            this._termoRel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoRel_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termoRel_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termoRel_ == child)
        {
            this._termoRel_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termoRel_ == oldChild)
        {
            setTermoRel((PTermoRel) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
