/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.node;

import compilador.analysis.*;

@SuppressWarnings("nls")
public final class ATlogTermoLog extends PTermoLog
{
    private PTermoLog _termoLog_;
    private POpLogico _opLogico_;
    private PTermoRel _termoRel_;

    public ATlogTermoLog()
    {
        // Constructor
    }

    public ATlogTermoLog(
        @SuppressWarnings("hiding") PTermoLog _termoLog_,
        @SuppressWarnings("hiding") POpLogico _opLogico_,
        @SuppressWarnings("hiding") PTermoRel _termoRel_)
    {
        // Constructor
        setTermoLog(_termoLog_);

        setOpLogico(_opLogico_);

        setTermoRel(_termoRel_);

    }

    @Override
    public Object clone()
    {
        return new ATlogTermoLog(
            cloneNode(this._termoLog_),
            cloneNode(this._opLogico_),
            cloneNode(this._termoRel_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseATlogTermoLog(this);
    }

    public PTermoLog getTermoLog()
    {
        return this._termoLog_;
    }

    public void setTermoLog(PTermoLog node)
    {
        if(this._termoLog_ != null)
        {
            this._termoLog_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoLog_ = node;
    }

    public POpLogico getOpLogico()
    {
        return this._opLogico_;
    }

    public void setOpLogico(POpLogico node)
    {
        if(this._opLogico_ != null)
        {
            this._opLogico_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._opLogico_ = node;
    }

    public PTermoRel getTermoRel()
    {
        return this._termoRel_;
    }

    public void setTermoRel(PTermoRel node)
    {
        if(this._termoRel_ != null)
        {
            this._termoRel_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._termoRel_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._termoLog_)
            + toString(this._opLogico_)
            + toString(this._termoRel_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._termoLog_ == child)
        {
            this._termoLog_ = null;
            return;
        }

        if(this._opLogico_ == child)
        {
            this._opLogico_ = null;
            return;
        }

        if(this._termoRel_ == child)
        {
            this._termoRel_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._termoLog_ == oldChild)
        {
            setTermoLog((PTermoLog) newChild);
            return;
        }

        if(this._opLogico_ == oldChild)
        {
            setOpLogico((POpLogico) newChild);
            return;
        }

        if(this._termoRel_ == oldChild)
        {
            setTermoRel((PTermoRel) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
