/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.analysis;

import compilador.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseTPrograma(TPrograma node);
    void caseTVar(TVar node);
    void caseTInicio(TInicio node);
    void caseTFim(TFim node);
    void caseTEol(TEol node);
    void caseTDeclPrograma(TDeclPrograma node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
