/* This file was generated by SableCC (http://www.sablecc.org/). */

package compilador.analysis;

import compilador.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseADeclPrograma(ADeclPrograma node);
    void caseADeclaracao(ADeclaracao node);

    void caseTNumber(TNumber node);
    void caseTUnderscore(TUnderscore node);
    void caseTCharmin(TCharmin node);
    void caseTCharmai(TCharmai node);
    void caseTEol(TEol node);
    void caseTPonto(TPonto node);
    void caseTDoispontos(TDoispontos node);
    void caseTPrograma(TPrograma node);
    void caseTInicio(TInicio node);
    void caseTFim(TFim node);
    void caseTVar(TVar node);
    void caseTDefTipo(TDefTipo node);
    void caseTTipo(TTipo node);
    void caseEOF(EOF node);
    void caseInvalidToken(InvalidToken node);
}
